还原部分更改

diff --git a/.github/workflows/auto_package.yml b/.github/workflows/auto_package.yml
--- a/.github/workflows/auto_package.yml
+++ b/.github/workflows/auto_package.yml
@@ -191,47 +191,21 @@ jobs:
           )
         shell: cmd
 
-      - name: Install Openssl
-        run: |
-          # Ensure OpenSSL is installed
-          choco install openssl
-
-          # Add OpenSSL bin directory to PATH
-          refreshenv
-        shell: cmd
-
-      - name: Merge certificate and private key into PFX
-        run: |
-          # Refresh environment variables
-          refreshenv
-
-          # Check if OpenSSL is available
-          where openssl
-          if %ERRORLEVEL% NEQ 0 (
-            echo "Error: OpenSSL not found in PATH."
-            exit 1
-          )
-
-          # Convert .cer and .pvk to .pfx
-          C:\OpenSSL-Win64\bin\openssl.exe pkcs12 -export -out "%GITHUB_WORKSPACE%\sign\root.pfx" -in "%GITHUB_WORKSPACE%\sign\root.cer" -inkey "%GITHUB_WORKSPACE%\sign\root.pvk" -passout pass:$env:SIGN_KEY
-
-          # Check if the .pfx file exists
-          if not exist "%GITHUB_WORKSPACE%\sign\root.pfx" (
-            echo "Error: .pfx file not created."
-            exit 1
-          )
-
-          echo "Certificate file 'root.pfx' created successfully."
-        shell: cmd
-
       - name: Install certificate
         run: |
-          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pfx'
+          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.cer'
+          $PRIVATE_KEY_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pvk'
           $PASSWORD = ConvertTo-SecureString -String $env:SIGN_KEY -AsPlainText -Force
           if (Test-Path $CERTIFICATE_PATH) {
-            Import-PfxCertificate -FilePath $CERTIFICATE_PATH -Password $PASSWORD -CertStoreLocation Cert:\CurrentUser\My
+            Import-Certificate -FilePath $CERTIFICATE_PATH -CertStoreLocation Cert:\CurrentUser\My
           } else {
-            Write-Host "Error: Certificate file 'root.pfx' not found."
+            Write-Host "Error: Certificate file 'root.cer' not found."
+            exit 1
+          }
+          if (Test-Path $PRIVATE_KEY_PATH) {
+            Import-PfxCertificate -FilePath $PRIVATE_KEY_PATH -Password $PASSWORD -CertStoreLocation Cert:\CurrentUser\My
+          } else {
+            Write-Host "Error: Private key file 'root.pvk' not found."
             exit 1
           }
         shell: powershell
@@ -239,19 +213,22 @@ jobs:
       - name: Sign Suya_Downloader executable
         run: |
           $SIGN_TOOL_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\signtool.exe'
-          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pfx'
+          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.cer'
+          $PRIVATE_KEY_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pvk'
           Write-Host "Certificate Path: $CERTIFICATE_PATH"
-          & $SIGN_TOOL_PATH sign /f $CERTIFICATE_PATH /p $env:SIGN_KEY /n "MY" /v /d "Suya Downloader" /tr http://timestamp.digicert.com /td SHA256 (Join-Path $env:GITHUB_WORKSPACE 'dist\Suya_Downloader.exe')
+          Write-Host "Private Key Path: $PRIVATE_KEY_PATH"
+          & $SIGN_TOOL_PATH sign /f $CERTIFICATE_PATH /p $env:SIGN_KEY /k $PRIVATE_KEY_PATH /n "MY" /v /d "Suya Downloader" /tr http://timestamp.digicert.com /td SHA256 (Join-Path $env:GITHUB_WORKSPACE 'dist\Suya_Downloader.exe')
         shell: powershell
 
       - name: Sign Updater executable
         run: |
           $SIGN_TOOL_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\signtool.exe'
-          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pfx'
+          $CERTIFICATE_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.cer'
+          $PRIVATE_KEY_PATH = Join-Path $env:GITHUB_WORKSPACE 'sign\root.pvk'
           Write-Host "Certificate Path: $CERTIFICATE_PATH"
-          & $SIGN_TOOL_PATH sign /f $CERTIFICATE_PATH /p $env:SIGN_KEY /n "MY" /v /d "Updater" /tr http://timestamp.digicert.com /td SHA256 (Join-Path $env:GITHUB_WORKSPACE 'dist\Updater.exe')
+          Write-Host "Private Key Path: $PRIVATE_KEY_PATH"
+          & $SIGN_TOOL_PATH sign /f $CERTIFICATE_PATH /p $env:SIGN_KEY /k $PRIVATE_KEY_PATH /n "MY" /v /d "Updater" /tr http://timestamp.digicert.com /td SHA256 (Join-Path $env:GITHUB_WORKSPACE 'dist\Updater.exe')
         shell: powershell
-
 
       - name: Zip the dist directory
         run: |
